name: package

on:

  # Workflow run will run after another job has completed
  # so we wait for the workflow to complete then get going
  workflow_run:
    workflows:
      - 'testing'

    branches:
      - 'master'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

    types:
      - completed

jobs:
  package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Java Setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: package
        working-directory: freemarker-wrapper/
        run: |
          mvn -B package --file pom.xml

      - name: add build details
        run: |
          pip install --pre hamlet-cli
          hamlet engine add-engine-source-build

      - name: upload build details
        uses: actions/upload-artifact@v2
        with:
          name: build-details
          path: .hamlet/engine_source.json

      - name: upload wrapper
        uses: actions/upload-artifact@v2
        with:
          name: engine-wrapper
          path: freemarker-wrapper/target/freemarker-wrapper-*.jar


  release_tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
    needs:
      - package
    runs-on: ubuntu-latest

    steps:
      - name: Get wrapper
        uses: actions/download-artifact@v2
        with:
          name: engine-wrapper
          path: ./

      - name: Create Releases
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: '**/*.jar'
          token: ${{ secrets.GITHUB_TOKEN }}


  docker_build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs:
      - package

    steps:

      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get wrapper
        uses: actions/download-artifact@v2
        with:
          name: engine-wrapper
          path: ./

      - name: get build details
        uses: actions/download-artifact@v2
        with:
          name: build-details
          path: ./.hamlet/

      - id: get_tag_name
        name: image tag prefix
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo ::set-output name=TAG_NAME::latest
            echo ::set-output name=PUSH_IMAGE::true
            exit 0
          fi

          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
            echo ::set-output name=PUSH_IMAGE::true
            exit 0
          fi

          echo ::set-output name=TAG_NAME::test
          echo ::set-output name=PUSH_IMAGE::false

      - id: find_wrapper_file
        name: find_wrapper_file
        run: |
          echo ::set-output NAME=WRAPPER_FILE_NAME::$(ls | grep freemarker-wrapper*.jar)


      - name: build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: "ghcr.io/${{github.repository}}:${{ steps.get_tag_name.outputs.TAG_NAME }}"
          push: ${{ startsWith(steps.get_tag_name.outputs.PUSH_IMAGE, 'true') }}
          target: base_package
          build-args: |
            wrapper_file_name=${{steps.find_wrapper_file.outputs.WRAPPER_FILE_NAME}}
